### ISSUE TITLE
Download button in VS Gallery is broken

### ISSUE THREAD

**Issue by pgorbas** [ligershark/CoreTemplatePack#14]
### Steps to recreate
1. Navigate to [https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ASPNETCoreTemplatePack](url) or click the link in your main page
2. Click the download button at the top of the page

### Current behavior
No download starts, it just redirects the browser to the same page

### Expected behavior
Download of the file should be started.

**Comment by madskristensen** [comment]
This bug has been reported to the VS Marketplace website. Closing the bug here since it has nothing to do with this extension
