### ISSUE TITLE
Debbugging is not working in Visual Studio

### ISSUE THREAD

**Issue by rsheptolut** [ligershark/CoreTemplatePack#16]
### Installed product versions
- Visual Studio: 2015 update 3
- This extension: 1.1.37
- Type Script tools 2.0.3

### Description
Can't get debugging of TypeScript to work for this template in Visual Studio + IE. Is it even supposed to work? I know this is probably not the correct place to report this problem, but maybe you know some secret recipe for things to finally just work in this mad new world? )) At least you appear to know something about how this webpack nightmare works and what it actually does, maybe it's not placing some files in the correct places that VS expect...

### Steps to recreate
1. Create a new project
2. Set a breakpoint somewhere in a method in *.component.ts 

### Current behavior
Visual studio sets an "empty" breakpoint (it becomes empty after starting the project) that says this in the tooltip: "The breakpoint will not currently be hit. No symbols have been loaded for this document."

### Expected behavior
Working breakpoints and debugging

**Comment by rsheptolut** [comment]
I'll answer my own issue, if no one is against it.

For me, what worked is I've replaced `inline-source-map` with `source-map` in webpack.config.js
The debugging started working (only in IE, of course...), because that's what's in `tsconfig.json`: `"sourceMap": true,`. I tried to do the opposite: specify `"inlineSourceMap"` for `tsconfig.json`, but that didn't work.

Is this a bug of the template? Tsc compiles to sourcemaps and webpack expects inline ones, or something? Or Visual Studio just can't handle inline source maps? I don't actually understand any of this stuff, just doing this by trial and error.

**Comment by SteveSandersonMS** [comment]
There's a guide to enabling debugging here: https://github.com/aspnet/JavaScriptServices/blob/dev/src/Microsoft.AspNetCore.SpaServices/README.md#debugging-your-projects

Please note that the VS project template in this repo is slightly out of date compared with the Yeoman generator, so you might want to consider using the Yeoman generator (generator-aspnetcore-spa) instead until we update the VS template.

**Comment by SteveSandersonMS** [comment]
> Or Visual Studio just can't handle inline source maps?

VS is quite fussy about what exact format of inline source map you need. Most of the things you might try won't work (e.g., the default output from the most obvious Webpack config). Although there is a certain structure to an inline source map that does work, it involves rewriting file paths during the build, so I've found it much simpler and more reliable just to use external source maps.
