### ISSUE TITLE
ASP.NET server not launching (VueJS template)

### ISSUE THREAD

**Issue by ghost** [ligershark/CoreTemplatePack#18]
### Installed product versions
- Visual Studio: 2015 Community
- This extension: 1.1.37

### Description
The server is not launching, only webpack dev server is running

### Steps to recreate
1. Create project with VueJS template
2. Put a breakpoint
3. Run in VS
4. breakpoint won't be hit, app won't start

### Current behavior
Only webpack server is running

### Expected behavior
Webpack server should run, in addition to ASP.NET Core server

**Comment by waynebrantley** [comment]
What is the process here?   
It seems that since webpack is running and serving the javascript/webpacked assets, you need to use it.  However, you of course also have to run your asp.net core (or noncore) site.   So are you supposed to point your javascript references to the webpack server at development time?

**Comment by ghost** [comment]
I have resolved this, sorry I left the issue open.

**Comment by waynebrantley** [comment]
@0xFireball Since you resolved it - can you answer my question?  What is your process?  I am a bit confused and was tagging onto your thread.  :-)

**Comment by ghost** [comment]
Hey @waynebrantley ,

What I was actually looking for was Vue.js + Webpack + hot module reload, like your Angular 2 template. But right now it looks like your template for Vue.js is just the official Vue webpack template :)
This is fine if you're just running a Vue site and the .NET server independently, but I wanted integration with a NancyFx backend.

It took me a little bit of playing around, but I got everything working satisfactorily:

A project (template?) with Vue.js and NancyFx: https://github.com/0xFireball/VueAndNfx
A blog post explaining how to set it up: https://blog.iridiumion.xyz/2016/12/asp-net-core-with-vue-js-webpack-and-hot-module-reloading-part-2/
A sample URL shortener application made with Vue.js, Webpack, and ASP.NET Core: https://github.com/0xFireball/YetAnotherShrinker
