### ISSUE TITLE
Client side Typescript debugging for Angular2 Applications not available

### ISSUE THREAD

**Issue by marxxxx** [ligershark/CoreTemplatePack#20]
### Installed product versions
- Visual Studio 2015 Enterprise
- This extension: 1.1.37

### Description
How to enable client side Typescript debugging for Angular2 Applications?

### Steps to recreate
1. Create a new Project using this template
2. Create Breakpoint in file counter.component.ts at method "incrementCounter()"
3. Press F5 to run 
4. Navigate to "Counter" Page and press the "Increment" Button

### Current behavior
The breakpoint is not hit. Hovering over the breakpoint will display the message "The breakpoint will not currently be hit. No symbols have been loaded for this document.

### Expected behavior
I would like to have client side typescript debugging enabled as well as server side ASP.NET Core debugging.
So i would expect the breakpoint to be hit and the execution to pause at this breakpoint.

**Comment by SteveSandersonMS** [comment]
There's a guide to enabling debugging here: https://github.com/aspnet/JavaScriptServices/blob/dev/src/Microsoft.AspNetCore.SpaServices/README.md#debugging-your-projects

Please note that the VS project template in this repo is slightly out of date compared with the Yeoman generator, so you might want to consider using the Yeoman generator (`generator-aspnetcore-spa`) instead until we update the VS template.

**Comment by marxxxx** [comment]
thank you, steve! i updated my vs template generated project according to the yeoman one (webpack config and npm packages) and now i can debug from vscode which is great :)
