### ISSUE TITLE
Webpack isn't updating the vendor.js

### ISSUE THREAD

**Issue by jaytonic** [ligershark/CoreTemplatePack#30]
### Installed product versions
- Visual Studio: VS 2015 Community Update 3
- This extension: 1.1.37

### Description
I created a new Asp.NET core Angular 2 starter application with this template. I removed bootstrap and added the materialize-css, but the generated file still contains the bootstrap and not materialize.

### Steps to recreate
1. Create a new Asp.NET core Angular 2 starter application 
2. In package.json, remove bootstrap and addd `"materialize-css":"0.98.0"`
3. In `webpack.config.vendor.js` remove the two lines concerning bootstrap(in the vendor array).
4. In `webpack.config.vendor.js` add the following two lines(in the vendor array):
```
'materialize-css',
'materialize-css/dist/css/materialize.css',
```
5. Build the solution
6. Check the `wwwroot/dist/vendor.css` file.

### Current behavior
Bootstrap classes are still present and materialize-css classes are not.

### Expected behavior
materialize-css classes should be present and bootstrap classes not.

Note: I'm kind of starting with all this webpack/npm/... stuff and I like it, but probably I did miss something? Is there a step that I should do manually to update this pack? If yes what? It makes 2 days I'm searching for it.

Note2: I'm still in a development stage, not production.

My current code is available on GH if you want to check something: https://github.com/jgrossrieder/PokerScrum

**Comment by neil-gilbert** [comment]
Have you tried running "webpack --config webpack.config.vendor.js" from the command prompt?

**Comment by jaytonic** [comment]
@neilgibert1234  This works, but I've expecting this to be done automatically by webpack + HMR?

**Comment by neil-gilbert** [comment]
No it's setup so HMR will work with all your files but not any 3rd party scripts otherwise webpack would have to  build everything (angular, etc) each time you make a change to your code.
I would recommend re-reading Stevens posts about how its all setup : http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/

**Comment by jaytonic** [comment]
@neilgibert1234 This link was really interessting, thank you very much, it answered my question and some others(like deployement to azure)!
