### ISSUE TITLE
Package restore fails after creating Angular 2 Starter Application

### ISSUE THREAD

**Issue by jooooel** [ligershark/CoreTemplatePack#6]
### Installed product versions
- Visual Studio: Update 3
- This extension: 1.1.37
- cmd.exe dotnet --version gives "1.0.0-preview2-003133"
### Description

Package restore fails on:
Microsoft.AspNetCore.AngularServices
Microsoft.Extensions.Configuration.CommandLine
with error message: 
"Unable to resolve 'Microsoft.AspNetCore.AngularServices (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'."
### Steps to recreate
1. Install extension
2. Create new Angular 2 Starter Application
3. Restore will commence automatically
4. Restore fails

Do I have a version mismatch somewhere? How can I debug this further?

**Update:**
Came back to work the next day. Tried to Restore Packages by right clicking "References" in the projects. Works just fine now :)

**Comment by MikeInSwitzerland** [comment]
Why was this article Closed ?  I've just installed the latest ASP.Net Core updates, created my first "**ASP.Net Core Angular 2 Starter Application (.Net Core)**" project in VS2015 Update 3, and get this same error.

```
log  : Restore failed in 15385ms.
Errors in C:\Projects\DotNetCoreAngular2ApplicationTest\DotNetCoreAngular2ApplicationTest\DotNetCoreAngular2ApplicationTest.xproj
    Unable to resolve 'Microsoft.AspNetCore.AngularServices (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.

```

**Comment by jimbo74** [comment]
I get this same issue
